POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john_doe@mail.com",
  "password": "123456"
}

###

POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  "email": "john_doe@mail.com",
  "password": "123456"
}